export const AUTH_ACCOUNT_REPOSITORY = Symbol('AUTH_ACCOUNT_REPOSITORY');
export const EMAIL_SENDER = Symbol('EMAIL_SENDER');
export const EMAIL_VERIFICATION_TOKEN_REPOSITORY = Symbol(
  'EMAIL_VERIFICATION_TOKEN_REPOSITORY',
);
export const AUTH_RATE_LIMITER = Symbol('AUTH_RATE_LIMITER');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const PASSWORD_RESET_TOKEN_REPOSITORY = Symbol(
  'PASSWORD_RESET_TOKEN_REPOSITORY',
);
export const RATE_LIMITER = Symbol('RATE_LIMITER');
export const SESSION_REPOSITORY = Symbol('SESSION_REPOSITORY');
export const TOKEN_HASHER = Symbol('TOKEN_HASHER');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const UNIT_OF_WORK = Symbol('UNIT_OF_WORK');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const POST_REPOSITORY = Symbol('POST_REPOSITORY');
export const POST_FEED_CACHE = Symbol('POST_FEED_CACHE');
export const POST_FEED_JOB_QUEUE = Symbol('POST_FEED_JOB_QUEUE');
export const FILE_STORAGE = Symbol('FILE_STORAGE');
export const OAUTH_SESSION_HANDOFF_STORE = Symbol(
  'OAUTH_SESSION_HANDOFF_STORE',
);
