ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POST_REPORT_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POST_REPORT_CANCELED';

ALTER TYPE "ReportStatus" ADD VALUE IF NOT EXISTS 'CANCELED';
