import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/shared/lib/utils";
import { QueryProvider } from "@/app/providers/query-provider";
import { I18nProvider } from "@/shared/i18n";
import { getServerLanguage } from "@/shared/i18n/server";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeBootstrapScript = `
  (function () {
    try {
      var storedTheme = localStorage.getItem("social-web:theme") || "system";
      var storedFontSize = parseInt(localStorage.getItem("social-web:font-size") || "16", 10);
      var cookieLanguageMatch = document.cookie.match(/(?:^|; )social-web-language=([^;]+)/);
      var cookieLanguage = cookieLanguageMatch ? decodeURIComponent(cookieLanguageMatch[1]) : "";
      var storedLanguage = cookieLanguage || localStorage.getItem("social-web:language") || "vi";
      var systemTheme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
      var theme = storedTheme === "dark" || storedTheme === "light" ? storedTheme : systemTheme;
      var fontSize = Number.isFinite(storedFontSize) ? Math.min(20, Math.max(14, storedFontSize)) : 16;
      var language = storedLanguage === "en" ? "en" : "vi";
      document.documentElement.lang = language;
      document.documentElement.dataset.theme = theme;
      document.documentElement.style.setProperty("--app-font-size", fontSize + "px");
      document.documentElement.classList.toggle("dark", theme === "dark");
    } catch (_) {}
  })();
`;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const language = await getServerLanguage();

  return (
    <html
      lang={language}
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeBootstrapScript }} />
      </head>
      <body className="flex min-h-full flex-col">
        <I18nProvider initialLanguage={language}>
          <QueryProvider>{children}</QueryProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
