export enum ErrorCode {
  // =====================
  // SYSTEM
  // =====================
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  STORAGE_ERROR = 'STORAGE_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // =====================
  // AUTH
  // =====================
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSE_DETECTED = 'REFRESH_TOKEN_REUSE_DETECTED',
  INVALID_OAUTH_PROFILE = 'INVALID_OAUTH_PROFILE',
  INVALID_OAUTH_STATE = 'INVALID_OAUTH_STATE',
  OAUTH_PROVIDER_NOT_CONFIGURED = 'OAUTH_PROVIDER_NOT_CONFIGURED',
  FORBIDDEN = 'FORBIDDEN',

  // =====================
  // USER
  // =====================
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_DISABLED = 'USER_DISABLED',
  USER_EMAIL_NOT_VERIFIED = 'USER_EMAIL_NOT_VERIFIED',
  INVALID_USER_ID = 'INVALID_USER_ID',

  // =====================
  // INPUT VALIDATION (DOMAIN)
  // =====================
  INVALID_EMAIL = 'INVALID_EMAIL',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  INVALID_USERNAME = 'INVALID_USERNAME',
  INVALID_FULLNAME = 'INVALID_FULLNAME',

  // =====================
  // BUSINESS LOGIC
  // =====================
  OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  // =====================
  // DATABASE SPECIFIC (optional but useful)
  // =====================
  DUPLICATE_FIELD = 'DUPLICATE_FIELD',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',

  // =====================
  // AUTHORIZATION (RBAC)
  // =====================
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  ROLE_NOT_ALLOWED = 'ROLE_NOT_ALLOWED',
}
